### ISSUE TITLE
Overlay rendering IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Nightfirecat** [damencs/spawn-predictor#2]
I didn't notice any issues while using the plugin, but I did get a lot of this in my logs:
```
2023-01-14 22:28:16 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.IndexOutOfBoundsException: Index 63 out of bounds for length 63
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.spawnpredictor.overlays.DisplayModeOverlay.render(DisplayModeOverlay.java:94)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:735)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:328)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:235)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:480)
	at hc.af(hc.java:13486)
	at bj.hb(bj.java:4626)
	at ay.kv(ay.java:10421)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ay.kv(ay.java:10452)
	at ce.ke(ce.java:10310)
	at client.hq(client.java:4330)
	at client.ab(client.java:1126)
	at an.am(an.java:416)
	at an.run(an.java:370)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rdutta** [comment]
Also getting this in logs.

**Comment by damencs** [comment]
@Nightfirecat / @rdutta - were you getting these from actually being inside the Fight Caves? Did you notice it whenever you were in the final wave and it started to print out?

**Comment by Nightfirecat** [comment]
No idea, I've since uninstalled the plugin since I only used it during a couple combat achievements and have no need to use it otherwise.
